# Generated by Django 3.0.3 on 2022-06-01 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hh_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hh_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.TextField()),
                ('skill_count', models.PositiveIntegerField()),
                ('skill_persent', models.PositiveIntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Hh_Request')),
            ],
        ),
    ]
